const LOSTFOUND_ITEMS = [
  {
    id: '1',
    datefound: '1/1/2020',
    valuable: 'Pair of earings',
    nonvaluable: '',
    perishable: '',
    area: 'Washroom',
    finder: 'John',
    claimedby: '',
    dateclaimed: '',
  },
  {
    id: '2',
    datefound: '1/10/2020',
    valuable: '',
    nonvaluable: 'Umbrella',
    perishable: '',
    area: 'In the front of Lobby',
    finder: 'Smith',
    claimedby: '',
    dateclaimed: '',
  },
  {
    id: '3',
    datefound: '1/15/2020',
    valuable: '',
    nonvaluable: '',
    perishable: 'Pack of cigarette',
    area: 'Beside Tim Hortons Level 1',
    finder: 'Peter',
    claimedby: '',
    dateclaimed: '',
  },
  {
    id: '4',
    datefound: '1/20/2020',
    valuable: 'Wallet with money',
    nonvaluable: 'Bag',
    perishable: 'Fruits',
    area: 'Left inside the Cinema',
    finder: 'Peter',
    claimedby: '',
    dateclaimed: '',
  },
];

export default LOSTFOUND_ITEMS;
